//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matricula()
        {
            this.Calificacions = new HashSet<Calificacion>();
        }
    
        public int idmatricula { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string estado { get; set; }
        public string tipo { get; set; }
        public Nullable<int> idalumno { get; set; }
        public Nullable<int> idmateria { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion> Calificacions { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
